"""initial

Revision ID: 7cd1f3bfcf26
Revises: 
Create Date: 2026-06-25 13:22:44.060006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd1f3bfcf26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.String(length=36), nullable=False),
    sa.Column('sport_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('verification_otp', sa.String(length=10), nullable=True),
    sa.Column('is_verified', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('leaderboard',
    sa.Column('leaderboard_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('leaderboard_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('sport_id', sa.String(length=36), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('team_logo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('sport_id', sa.String(length=36), nullable=True),
    sa.Column('tournament_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.Column('team1_id', sa.String(length=36), nullable=True),
    sa.Column('team2_id', sa.String(length=36), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('question_text', sa.String(length=500), nullable=True),
    sa.Column('option1', sa.String(length=100), nullable=True),
    sa.Column('option2', sa.String(length=100), nullable=True),
    sa.Column('option3', sa.String(length=100), nullable=True),
    sa.Column('option4', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('selected_option', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('user_answers',
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('selected_option', sa.String(length=100), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('history')
    op.drop_table('questions')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('leaderboard')
    op.drop_table('users')
    op.drop_table('sports')
    op.drop_table('admins')
    # ### end Alembic commands ###
